# 服务配置 http配置和GRPC接口配置
server:
  port: 18080
  compression:
    enabled: true
    mime-types: application/json,application/octet-stream

grpc:
  server:
    port: 9898   #发布远程访问地址
    in-process-name: native  #发布本地访问地址
  client:
    inProcess: #自定义的客户端名称
      address: in-process:native #配置内部访问服务名称
      enableKeepAlive: true
      keepAliveWithoutCalls: true

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    org.springframework.web: ERROR

app-properties:
  token-key: token
  http-api-path: /api/**

# spring配置
spring:
  application:
    name: GrpcFramework-Server-APP
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/badCase?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      max-pool-prepared-statement-per-connection-size: 5
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      filters: stat

# mybatis-plug 配置
mybatis-plus:
  mapper-locations: classpath:/mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名规则映射
    default-statement-timeout: 20000 #超时查询
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志

# swagger 自定义配置，为了扩展base-package功能
swagger-config:
  enabled: true #正式环境需要设置为false
  title: GrpcFramework-API
  description: GrpcFramework-Server-Restful-API
  version: V1.0
  base-package: com.zd.baseframework.core.restful #多个base包可用逗号分隔
  authorization-key-name: token